name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: create env file
        run: echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ./Dockerfile
          platform: linux/arm64/v8,linux/amd64
          push: true
          tags: shinhyeok/dobda-server:latest
